FROM tkachuklabs/ubuntu-16.04-stack:2019-01-06
MAINTAINER ILJA TKACHUK <tkachuk.labs@gmail.com>

RUN git clone https://github.com/timCF/keter.git && \
    cd ./keter && \
    git checkout 9502983e20e613738221974d281cb87273a6f941 && \
    stack install && \
    cd .. && \
    rm -rf ./keter

WORKDIR /root
CMD ["bash"]
